# Generated by Django 5.1 on 2024-08-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=122)),
                ('item_desc', models.CharField(max_length=122)),
                ('item_price', models.IntegerField()),
            ],
        ),
    ]
